on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      contents: write
    steps:
      - name: Update ubuntu packages
        run: sudo apt-get update

      - name: Install ubuntu dependencies
        run:  sudo apt-get install libcgal-dev libglu1-mesa-dev libcurl4-openssl-dev zlib1g-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Setup Miniconda"
        uses: "conda-incubator/setup-miniconda@v2"
        with:
          activate-environment: custom-env
          environment-file: environment.yml
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        run: quarto render . --profile production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
